BT_GATT_SERVICE_DEFINE(fota_svc,
	BT_GATT_PRIMARY_SERVICE(BT_UUID_FOTA_SERVICE),

	BT_GATT_CHARACTERISTIC(BT_UUID_FOTA_CONTROL,
		BT_GATT_CHRC_WRITE,
		BT_GATT_PERM_WRITE,
		NULL, fota_control_write, NULL),

	BT_GATT_CHARACTERISTIC(BT_UUID_ECU_ID,
		BT_GATT_CHRC_WRITE,
		BT_GATT_PERM_WRITE,
		NULL, ecu_id_write, NULL),

	BT_GATT_CHARACTERISTIC(BT_UUID_IMAGE_METADATA,
		BT_GATT_CHRC_WRITE,
		BT_GATT_PERM_WRITE,
		NULL, image_metadata_write, NULL),

	BT_GATT_CHARACTERISTIC(BT_UUID_ACTIVE_BLOCK_ADDR,
		BT_GATT_CHRC_WRITE,
		BT_GATT_PERM_WRITE,
		NULL, active_block_addr_write, NULL),

	BT_GATT_CHARACTERISTIC(BT_UUID_FIRMWARE_DATA,
		BT_GATT_CHRC_WRITE_WITHOUT_RESP,
		BT_GATT_PERM_WRITE,
		NULL, firmware_data_write, NULL),

	BT_GATT_CHARACTERISTIC(BT_UUID_FOTA_STATUS,
		BT_GATT_CHRC_READ | BT_GATT_CHRC_NOTIFY,
		BT_GATT_PERM_READ,
		fota_status_read, NULL, NULL),
	BT_GATT_CCC(NULL, BT_GATT_PERM_READ | BT_GATT_PERM_WRITE),

	BT_GATT_CHARACTERISTIC(BT_UUID_FOTA_PROGRESS,
		BT_GATT_CHRC_NOTIFY,
		BT_GATT_PERM_NONE,
		NULL, NULL, NULL),
	BT_GATT_CCC(NULL, BT_GATT_PERM_READ | BT_GATT_PERM_WRITE),

	BT_GATT_CHARACTERISTIC(BT_UUID_RESUME_OFFSET,
		BT_GATT_CHRC_READ,
		BT_GATT_PERM_READ,
		resume_offset_read, NULL, NULL)
);
